import {test} from 'node:test';import assert from 'node:assert/strict';
import {teamMapping,pairedWindow,normalizeLiveEvidence,fetchMappedSnapshot} from './live-evidence.mjs';
import {TelemetryClient} from './telemetry.mjs';
function fixture(){const rows=[],dau=[];for(let i=0;i<56;i++){const d=new Date('2026-08-04T00:00:00Z');d.setUTCDate(d.getUTCDate()+i);const day=d.toISOString().slice(0,10);rows.push({event_date:day,total_suggested_diffs:100,total_accepted_diffs:50});dau.push({date:day,dau:1})}const users=[{id:'u1',email:'a@example.test'},{id:'u2',email:'b@example.test'}];return {roster:{teamMembers:users},window:{startDate:'2026-08-04',endDate:'2026-09-28'},periods:pairedWindow({startDate:'2026-09-01',endDate:'2026-09-28'}),commits:[{items:[]}],teamData:[{name:'Example',users,edits:{data:rows},dau:{data:dau}}]}}
test('live normalization shares evidence contract without fixed headcount',()=>{const e=normalizeLiveEvidence(fixture(),'version');assert.equal(e.teams[0].size,2);assert.equal(e.records.length,6);assert.equal(e.teams[0].a,50);assert.equal(e.teams[0].p,50);assert.equal(e.teams[0].u,50);assert.equal(e.account.score,50);assert.equal(e.source,'live');assert.equal(e.records[0].datasetVersion,'version');assert.match(e.records[0].sourceRefs[0],/telemetry-snapshot-version/)});
test('missing daily records and insufficient mapped coverage withhold scores',()=>{const s=fixture();s.teamData[0].dau.data=s.teamData[0].dau.data.slice(0,30);assert.equal(normalizeLiveEvidence(s,'v').account.score,null);const t=fixture();t.roster.teamMembers=[...t.roster.teamMembers,{id:'u3',email:'c@example.test'}];assert.equal(normalizeLiveEvidence(t,'v').account.score,null)});
test('mapping rejects unknown and duplicated identities and overly long paired windows',()=>{const roster=fixture().roster;assert.throws(()=>teamMapping('[{"name":"Team","userIds":["missing"]}]',roster),/unknown/);assert.throws(()=>teamMapping('[{"name":"Team","userIds":["u1","a@example.test"]}]',roster),/duplicated/);assert.throws(()=>pairedWindow({startDate:'2026-07-01',endDate:'2026-09-28'}),/forty-five/)});
test('duplicate daily records cannot inflate acceptance',()=>{const s=fixture();s.teamData[0].edits.data.push(s.teamData[0].edits.data[0]);assert.throws(()=>normalizeLiveEvidence(s,'v'),/Duplicate analytics/)});
test('mapped fetch sends authorized team filters and extends comparable baseline',async()=>{const s=fixture(),requests=[];const client=new TelemetryClient({key:'test',request:async url=>{const u=new URL(url);requests.push(u);if(u.pathname==='/teams/members')return Response.json(s.roster);if(u.pathname.includes('/by-user/'))return Response.json({data:{},pagination:{page:1,hasNextPage:false}});if(u.pathname.endsWith('/commits'))return Response.json({items:[],page:1,totalCount:0});return Response.json(u.pathname.endsWith('/dau')?s.teamData[0].dau:s.teamData[0].edits)}});const snapshot=await fetchMappedSnapshot(client,{startDate:'2026-09-01',endDate:'2026-09-28'},'[{"name":"Example","userIds":["u1","u2"]}]');assert.equal(snapshot.window.startDate,'2026-08-04');const filtered=requests.filter(u=>u.pathname.includes('/team/'));assert.equal(filtered.length,2);assert.ok(filtered.every(u=>u.searchParams.get('users')==='u1,u2'));assert.equal(normalizeLiveEvidence(snapshot,'v').account.score,50)});

