import {IntegrationError} from './telemetry.mjs';
export function endpoint(value){let url;try{url=new URL(value)}catch{throw new IntegrationError('Configure a valid MCP HTTPS endpoint.')}if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash||['localhost','127.0.0.1','[::1]'].includes(url.hostname))throw new IntegrationError('MCP endpoint must be HTTPS without credentials, query or fragment.');return url.href}
export async function mcpSession({url,token,request=fetch},operation){
 url=endpoint(url);const headers={'Content-Type':'application/json',Accept:'application/json, text/event-stream'};if(token)headers.Authorization='Bearer '+token;let sequence=0,session;
 async function rpc(method,params,notification=false){const id=++sequence,r=await request(url,{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',...(notification?{}:{id}),method,...(params?{params}:{})}),redirect:'error',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new IntegrationError(`MCP returned HTTP ${r.status}.`);if(notification){await r.body?.cancel();return null}if(!(r.headers.get('content-type')??'').includes('application/json')){await r.body?.cancel();throw new IntegrationError('Only MCP JSON responses are supported; streaming SSE requires another adapter.')}const text=await r.text();if(text.length>1_000_000)throw new IntegrationError('MCP response is too large.');let body;try{body=JSON.parse(text)}catch{throw new IntegrationError('Invalid MCP JSON response.')}if(body.jsonrpc!=='2.0'||body.id!==id||body.error||!body.result)throw new IntegrationError('MCP protocol request failed.');if(method==='initialize'){session=r.headers.get('mcp-session-id');if(session)headers['Mcp-Session-Id']=session}return body.result}
 try{const init=await rpc('initialize',{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'account-operations',version:'0.2.0'}});if(init.protocolVersion!=='2025-06-18'||!init.capabilities?.tools)throw new IntegrationError('MCP tools capability or protocol version is unsupported.');headers['MCP-Protocol-Version']='2025-06-18';await rpc('notifications/initialized',undefined,true);return await operation(rpc)}finally{if(session)try{const r=await request(url,{method:'DELETE',headers,redirect:'error',signal:AbortSignal.timeout(5000)});await r.body?.cancel()}catch{}}
}
export async function listTools(config){return mcpSession(config,async rpc=>{const tools=[],seen=new Set();let cursor;for(let page=0;page<20;page++){const result=await rpc('tools/list',cursor?{cursor}:{});if(!Array.isArray(result.tools)||result.tools.some(t=>typeof t.name!=='string'||!t.inputSchema))throw new IntegrationError('Unexpected MCP tool schema.');tools.push(...result.tools);if(!result.nextCursor)return tools;if(seen.has(result.nextCursor))throw new IntegrationError('Repeated MCP pagination cursor.');seen.add(result.nextCursor);cursor=result.nextCursor}throw new IntegrationError('MCP tool pagination limit reached.')})}
export async function callTool(config,name,args){return mcpSession(config,async rpc=>{const result=await rpc('tools/call',{name,arguments:args});return {isError:result.isError===true,contentItems:Array.isArray(result.content)?result.content.length:0}})}
