import {test} from 'node:test';import assert from 'node:assert/strict';
import {handleOperation,actionDigest,scheduledSyncAndDiagnose} from './operations.mjs';
import {TelemetryClient,explicitWindow} from './telemetry.mjs';
import {listTools} from './mcp.mjs';
function store(){const entries=new Map();return {async kvGet(k){return structuredClone(entries.get(k)??{revision:0,value:null})},async kvPut(k,r,v){if((entries.get(k)?.revision??0)!==r)return false;entries.set(k,{revision:r+1,value:structuredClone(v)});return true}}}
const env={SIGNAL_MCP_URL:'https://mcp.example.test/tools',SIGNAL_MCP_ALLOWED_TOOLS:'["create_ticket"]'};
function mcp({fail=false}={}){const calls=[];const request=async(url,opts)=>{if(opts.method==='DELETE')return new Response(null,{status:204});const body=JSON.parse(opts.body);calls.push(body);if(body.method==='notifications/initialized')return new Response(null,{status:202});if(body.method==='tools/call'&&fail)throw Error('timeout after side effect');const result=body.method==='initialize'?{protocolVersion:'2025-06-18',capabilities:{tools:{}}}:body.method==='tools/list'?{tools:[{name:'create_ticket',inputSchema:{type:'object',required:['title']}}]}:{content:[{type:'text',text:'sensitive result'}]};return Response.json({jsonrpc:'2.0',id:body.id,result},{headers:{'mcp-session-id':'test-session'}})};return {request,calls}}
async function prepared(options,dryRun=true){return handleOperation('prepare',{tool:'create_ticket',arguments:{title:'Reviewed title'},dryRun},options)}
test('status is unconfigured without credentials; no secrets exposed',async()=>{const s=await handleOperation('status',{}, {store:store(),env:{}});assert.equal(s.telemetry,'unconfigured');assert.equal(s.externalExecution,'dry-run only')});
test('read adapter follows pagination and fixed origin; malformed data rejected',async()=>{let calls=0;const client=new TelemetryClient({key:'secret',request:async(url,opts)=>{assert.equal(new URL(url).origin,'https://api.cursor.com');assert.equal(opts.redirect,'error');const page=Number(new URL(url).searchParams.get('page'));calls++;return Response.json({data:{'a@example.test':[{total_suggested_diffs:2,total_accepted_diffs:1}]},pagination:{page,hasNextPage:page===1}})}});assert.equal((await client.agentEdits({startDate:'2026-09-01',endDate:'2026-09-28'})).length,2);assert.equal(calls,2);assert.throws(()=>explicitWindow({startDate:'2026-02-30',endDate:'2026-03-02'}));await assert.rejects(()=>new TelemetryClient({key:'x',request:async()=>Response.json({items:[],page:1,totalCount:1})}).commits({startDate:'2026-09-01',endDate:'2026-09-28'}),/before totalCount/)});
test('dry run requires exact approval and does not call external tools',async()=>{const mock=mcp(),options={env,store:store(),request:mock.request,actor:'operator'},a=await prepared(options);await assert.rejects(()=>handleOperation('execute',{id:a.id,digest:a.digest},options),/approval/);await assert.rejects(()=>handleOperation('approve',{id:a.id,digest:'different',confirm:true},options),/changed/);await handleOperation('approve',{id:a.id,digest:a.digest,confirm:true},options);const done=await handleOperation('execute',{id:a.id,digest:a.digest},options);assert.equal(done.status,'dry-run');assert.equal(mock.calls.filter(x=>x.method==='tools/call').length,0);await assert.rejects(()=>handleOperation('execute',{id:a.id,digest:a.digest},options),/approval/)});
test('live execution claims atomically and uncertain result cannot retry',async()=>{const mock=mcp({fail:true}),options={env:{...env,SIGNAL_ALLOW_EXTERNAL_EXECUTION:'true'},store:store(),request:mock.request,actor:'operator'},a=await prepared(options,false);await handleOperation('approve',{id:a.id,digest:a.digest,confirm:true},options);await assert.rejects(()=>handleOperation('execute',{id:a.id,digest:a.digest},options),/uncertain/);await assert.rejects(()=>handleOperation('execute',{id:a.id,digest:a.digest},options),/approval/);assert.equal(mock.calls.filter(x=>x.method==='tools/call').length,1);const history=await handleOperation('history',{},options);assert.equal(history.actions[0].status,'unknown')});
test('allowlist and configuration changes revoke execution',async()=>{const mock=mcp(),options={env,store:store(),request:mock.request,actor:'operator'};await assert.rejects(()=>handleOperation('prepare',{tool:'delete_all',arguments:{}},options),/allowlist/);const a=await prepared(options);await handleOperation('approve',{id:a.id,digest:a.digest,confirm:true},options);await assert.rejects(()=>handleOperation('execute',{id:a.id,digest:a.digest},{...options,env:{...env,SIGNAL_MCP_URL:'https://different.example.test/'}}),/configuration changed/);assert.equal(await actionDigest({a:1,b:2}),await actionDigest({b:2,a:1}))});
test('concurrent execute requests send at most one tools/call',async()=>{const mock=mcp(),options={env:{...env,SIGNAL_ALLOW_EXTERNAL_EXECUTION:'true'},store:store(),request:mock.request,actor:'operator'},a=await prepared(options,false);await handleOperation('approve',{id:a.id,digest:a.digest,confirm:true},options);const results=await Promise.allSettled([1,2].map(()=>handleOperation('execute',{id:a.id,digest:a.digest},options)));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(mock.calls.filter(x=>x.method==='tools/call').length,1)});
test('scheduler never executes prepared actions and records unconfigured failure',async()=>{const storage=store();await assert.rejects(()=>scheduledSyncAndDiagnose({store:storage,env:{}}),/unconfigured/);const h=await handleOperation('history',{}, {store:storage,env:{}});assert.equal(h.lastSync.status,'failed');assert.equal(h.actions.length,0)});
test('MCP streaming response fails explicitly',async()=>{await assert.rejects(()=>listTools({url:env.SIGNAL_MCP_URL,request:async()=>new Response('data: x',{headers:{'content-type':'text/event-stream'}})}),/streaming SSE/) });
