// Server-only adapters; standard fetch/Web Crypto compatible with Node and Workers.
export class IntegrationError extends Error {constructor(message){super(message);this.name='IntegrationError'}}
export function explicitWindow({startDate,endDate}={}){
 const valid=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;
 if(!valid(startDate)||!valid(endDate)||startDate>endDate||(Date.parse(endDate)-Date.parse(startDate))/86400000>90)throw new IntegrationError('Use valid start/end ISO dates spanning at most 90 days.');
 return {startDate,endDate};
}
async function json(response){if(!response.ok)throw new IntegrationError(`Telemetry returned HTTP ${response.status}; no snapshot was published.`);const text=await response.text();if(text.length>5_000_000)throw new IntegrationError('Response exceeds the supported page size.');try{return JSON.parse(text)}catch{throw new IntegrationError('Telemetry returned invalid JSON.')}}
export class TelemetryClient {
 constructor({key,request=fetch,maxPages=100}={}){this.key=key;this.request=request;this.maxPages=maxPages}
 async get(path,params={}){if(!this.key)throw new IntegrationError('Developer-tool API is unconfigured. Set TELEMETRY_API_KEY on the server.');const url=new URL(path,'https://api.cursor.com');for(const [k,v]of Object.entries(params))url.searchParams.set(k,String(v));return json(await this.request(url.toString(),{headers:{Authorization:'Basic '+btoa(this.key+':')},redirect:'error',signal:AbortSignal.timeout(15000)}))}
 async roster(){const x=await this.get('/teams/members');if(!Array.isArray(x.teamMembers)||x.teamMembers.some(m=>typeof m.email!=='string'))throw new IntegrationError('Unexpected roster schema.');return x}
 async teamMetric(metric,window,users){if(!['agent-edits','dau'].includes(metric))throw new IntegrationError('Unsupported team metric.');const x=await this.get('/analytics/team/'+metric,{...explicitWindow(window),users:users.join(',')});if(!Array.isArray(x.data))throw new IntegrationError('Unexpected team analytics schema.');return x}
 async agentEdits(window){const pages=[];for(let page=1;page<=this.maxPages;page++){const x=await this.get('/analytics/by-user/agent-edits',{...explicitWindow(window),page,pageSize:100});if(!x.data||Array.isArray(x.data)||typeof x.data!=='object'||!x.pagination||x.pagination.page!==page||typeof x.pagination.hasNextPage!=='boolean'||Object.values(x.data).some(rows=>!Array.isArray(rows)||rows.some(r=>!Number.isFinite(r.total_suggested_diffs)||!Number.isFinite(r.total_accepted_diffs)||r.total_suggested_diffs<0||r.total_accepted_diffs<0||r.total_accepted_diffs>r.total_suggested_diffs)))throw new IntegrationError('Unexpected analytics schema.');pages.push(x);if(!x.pagination.hasNextPage)return pages}throw new IntegrationError('Analytics pagination limit reached; partial data not published.')}
 async commits(window){const pages=[];let seen=0;for(let page=1;page<=this.maxPages;page++){const x=await this.get('/analytics/ai-code/commits',{...explicitWindow(window),page,pageSize:100});if(!Array.isArray(x.items)||x.page!==page||!Number.isInteger(x.totalCount)||x.totalCount<0||x.items.some(r=>['totalLinesAdded','tabLinesAdded','composerLinesAdded'].some(k=>!Number.isFinite(r[k])||r[k]<0)||r.tabLinesAdded+r.composerLinesAdded>r.totalLinesAdded))throw new IntegrationError('Unexpected code-tracking schema.');pages.push(x);seen+=x.items.length;if(seen>=x.totalCount)return pages;if(!x.items.length)throw new IntegrationError('Code tracking pagination ended before totalCount.')}throw new IntegrationError('Code tracking pagination limit reached; partial data not published.')}
 async snapshot(window){explicitWindow(window);const roster=await this.roster(),agentEdits=await this.agentEdits(window),commits=await this.commits(window);return {source:'live',window,roster,agentEdits,commits,fetchedAt:new Date().toISOString()}}
}
export function summarizeTelemetry(snapshot){let suggested=0,accepted=0,added=0,ai=0;for(const page of snapshot.agentEdits)for(const rows of Object.values(page.data))for(const r of rows){suggested+=r.total_suggested_diffs;accepted+=r.total_accepted_diffs}for(const page of snapshot.commits)for(const r of page.items){added+=r.totalLinesAdded;ai+=r.tabLinesAdded+r.composerLinesAdded}return {source:'live',window:snapshot.window,fetchedAt:snapshot.fetchedAt,members:snapshot.roster.teamMembers.length,agentAcceptance:{numerator:accepted,denominator:suggested,value:suggested?accepted/suggested*100:null},aiCommitShare:{numerator:ai,denominator:added,value:added?ai/added*100:null},healthScore:null,diagnosis:'Live ingestion verified. Account score withheld: team mapping, active-share denominator and comparable baseline are not configured. No causal benefit is inferred.'}}
