import test from 'node:test';
import assert from 'node:assert/strict';
import {validEvidence,evidenceCurrent,linkMeasurement,reconcileEvidence,measurementKind,comparableMeasurements} from './evidence.mjs';
import {reviewFingerprint} from './outcome-review.mjs';
const e={id:'EV-1-current-agent_acceptance',datasetVersion:'v1',team:'Payments',metric:'agent_acceptance',unit:'%',value:50,numerator:50,denominator:100,window:{start:'2026-09-01',end:'2026-09-28'},sourceRefs:['fixtures/analytics.json','sql:acceptance'],eligible:true,period:'current'};
test('ineligible, missing and zero denominator evidence cannot populate measurements',()=>{for(const patch of [{eligible:false},{value:null},{denominator:0},{numerator:-1}]){assert.equal(validEvidence({...e,...patch}),false);assert.throws(()=>linkMeasurement({team:'Payments'},{...e,...patch}))}});
test('telemetry snapshots survive source changes and become stale',()=>{const d=linkMeasurement({team:'Payments'},e);assert.equal(measurementKind(d),'telemetry');assert.equal(evidenceCurrent(d.outcomeEvidence,{records:[e]}),true);assert.equal(evidenceCurrent(d.outcomeEvidence,{records:[{...e,datasetVersion:'v2'}]}),false);assert.equal(d.outcomeEvidence.datasetVersion,'v1')});
test('manual edits detach mismatched telemetry without losing unrelated fields',()=>{const d=linkMeasurement({team:'Payments',title:'Keep me'},e);const manual=reconcileEvidence({...d,actual:51});assert.equal(manual.outcomeEvidence,undefined);assert.equal(manual.measurementKind,'manual');assert.equal(manual.title,'Keep me');assert.notEqual(reviewFingerprint(d),reviewFingerprint(manual))});
test('wrong team evidence is rejected and identical windows are not a follow-up',()=>{assert.throws(()=>linkMeasurement({team:'Other'},e));const d=linkMeasurement(linkMeasurement({team:'Payments'},e,'baseline'),e);assert.equal(comparableMeasurements(d),false);const prior={...e,id:'prior',window:{start:'2026-08-04',end:'2026-08-31'}};assert.equal(comparableMeasurements(linkMeasurement(d,prior,'baseline')),true)});
