export function mountOperations(ctx){
 const {node,button}=ctx,section=node('section','');section.dataset.screen='operations';section.hidden=true;document.querySelector('main').append(section);const nav=node('button','Live operations','navbutton');nav.dataset.page='operations';document.querySelector('nav').append(nav);
 const status=node('pre','Configuration not loaded.','qbr-preview'),message=node('p','','small');message.setAttribute('role','status');
 async function api(action,body={}){const r=await fetch('/api/operations/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok||result.error)throw Error(result.error||'Operation failed.');return result}
 async function run(fn){message.textContent='Working…';try{await fn();message.textContent='Completed.'}catch(e){message.textContent=e.message}}
 const header=node('div','','heading');header.append(node('h1','Connect evidence. Review actions.'));section.append(header,node('p','Live adapters require server-side credentials. The portfolio dashboard remains synthetic. Sync stores a separate live snapshot; it does not silently replace the demonstration. No external action runs without an exact reviewed payload.','internal-banner'),button('Refresh configuration',()=>run(async()=>{status.textContent=JSON.stringify(await api('status'),null,2)})),status,message);
 const sync=node('article','','record');sync.append(node('h2','Read-only telemetry sync'));const start=node('input',''),end=node('input','');start.type=end.type='date';const today=new Date();today.setUTCDate(today.getUTCDate()-1);end.value=today.toISOString().slice(0,10);today.setUTCDate(today.getUTCDate()-27);start.value=today.toISOString().slice(0,10);for(const [text,input] of [['Start date',start],['End date',end]]){const label=node('label',text);label.append(input);sync.append(label)}sync.append(button('Sync and diagnose',()=>run(async()=>{status.textContent=JSON.stringify(await api('sync',{startDate:start.value,endDate:end.value}),null,2)})));section.append(sync);
 const card=node('article','','record');card.append(node('h2','Reviewed MCP action'));const tools=document.createElement('select'),toolLabel=node('label','Allowlisted tool');toolLabel.append(tools);const schema=node('pre','','qbr-preview');let available=[];tools.onchange=()=>{schema.textContent=JSON.stringify(available.find(t=>t.name===tools.value)?.inputSchema??{},null,2)};
 card.append(button('Discover allowed tools',()=>run(async()=>{available=(await api('tools')).tools;tools.replaceChildren(...available.map(t=>{const option=node('option',t.name);option.value=t.name;return option}));tools.onchange()})),toolLabel,schema);
 const args=document.createElement('textarea');args.value='{}';args.maxLength=16000;const argsLabel=node('label','Exact JSON arguments');argsLabel.append(args);const dry=document.createElement('input');dry.type='checkbox';dry.checked=true;const dryLabel=node('label','');dryLabel.append(dry,document.createTextNode(' Dry run: do not invoke the external tool.'));const exact=node('pre','No prepared action.','qbr-preview');let prepared=null;
 const confirmed=document.createElement('input');confirmed.type='checkbox';const confirmLabel=node('label','');confirmLabel.append(confirmed,document.createTextNode(' I reviewed this exact endpoint, tool, arguments and execution mode.'));
 const approve=button('Approve exact action',()=>run(async()=>{if(!prepared||!confirmed.checked)throw Error('Review and confirm the prepared action first.');prepared=await api('approve',{id:prepared.id,digest:prepared.digest,confirm:true});exact.textContent=JSON.stringify(prepared,null,2);approve.disabled=true;execute.disabled=false}));
 const execute=button('Execute approved action',()=>run(async()=>{if(!prepared)throw Error('Prepare and approve first.');execute.disabled=true;prepared=await api('execute',{id:prepared.id,digest:prepared.digest});exact.textContent=JSON.stringify(prepared,null,2)}));approve.disabled=execute.disabled=true;
 const invalidate=()=>{prepared=null;confirmed.checked=false;approve.disabled=execute.disabled=true;exact.textContent='Inputs changed. Prepare a new action.'};args.oninput=invalidate;dry.onchange=invalidate;const schemaChange=tools.onchange;tools.onchange=()=>{schemaChange();invalidate()};
 card.append(argsLabel,dryLabel,button('Prepare action for review',()=>run(async()=>{prepared=await api('prepare',{tool:tools.value,arguments:JSON.parse(args.value),dryRun:dry.checked});exact.textContent=JSON.stringify(prepared,null,2);confirmed.checked=false;approve.disabled=prepared.status!=='prepared';execute.disabled=true})),exact,confirmLabel,approve,execute);section.append(card);
 const history=node('pre','','qbr-preview');section.append(button('View normalized live evidence',()=>run(async()=>{history.textContent=JSON.stringify(await api('evidence'),null,2)})),button('Refresh durable action history',()=>run(async()=>{history.textContent=JSON.stringify(await api('history'),null,2)})),history);return {render(){}};
}
