import {canDeploy} from './deployment-readiness.mjs';
import {evidenceFingerprint,evidenceLabel,evidenceCurrent,measurementKind,measurementMatches,comparableMeasurements} from './evidence.mjs';
export function reviewFingerprint(d){return JSON.stringify([d.id,d.objective,d.metric,d.unit,d.direction,d.baseline,d.target,d.actual,d.observed,d.evidence,d.source,d.guardrail,d.quality,evidenceFingerprint(d.baselineEvidence),evidenceFingerprint(d.outcomeEvidence),d.recommendationEvidence?.map(evidenceFingerprint),d.hypothesisPlan,d.readiness,d.workflowOutcome])}
export function canExpand(d){return canDeploy(d)&&comparableMeasurements(d)&&(!d.outcomeEvidence||measurementMatches(d,d.outcomeEvidence))&& Number.isFinite(d.actual)&&!!d.observed&&!!d.evidence?.trim()&&d.quality==='Passed'&&(d.direction==='increase'?d.actual>=d.target:d.actual<=d.target)}
export function mountOutcomeReview(ctx){
 let selectedId=null;
 const {node,button,field}=ctx,section=node('section','');section.dataset.screen='outcomes';section.hidden=true;document.querySelector('main').append(section);const nav=node('button','04 · Outcome review','navbutton');nav.dataset.page='outcomes';document.querySelector('nav').append(nav);
 function evidenceDetails(d){const details=node('details','');details.append(node('summary','Evidence'),node('p',d.evidence),node('p','Measurement: '+measurementKind(d)+'; observational, not causal.'),node('p','Baseline: '+evidenceLabel(d.baselineEvidence)),node('p','Outcome: '+evidenceLabel(d.outcomeEvidence)));return details}
 function render(){section.replaceChildren();const head=node('div','','heading');head.append(node('h1','04 · Outcome review'),button('Continue to reviewed QBR →',()=>ctx.navigate('qbr')));section.append(head,node('p','Compare the result with the target. Choose the next step.','small'));if(selectedId)section.append(button('Show all outcomes',()=>{selectedId=null;render()}));const grid=node('div','','record-grid');section.append(grid);
 for(const d of ctx.getWorkspace().deployments.filter(d=>!selectedId||d.id===selectedId)){const r=ctx.getWorkspace().outcomeReviews?.find(x=>x.deploymentId===d.id),card=node('article','','record');card.append(node('div',d.id,'eyebrow'),node('h2',d.title),node('p',`${d.metric}: baseline ${d.baseline}; target ${d.target}; observed ${d.actual??'unavailable'} ${d.unit}.`),node('p',`${ctx.outcome(d)} · Guardrail: ${d.quality}`),evidenceDetails(d),node('p',r?((r.evidenceSnapshot===reviewFingerprint(d)&&(!d.outcomeEvidence||evidenceCurrent(d.outcomeEvidence,ctx.getEvidence?.())))?'Current review: '+r.decision:'Review outdated — source changed'):'Not reviewed','badge'));if(ctx.openIntervention)card.append(button('Open intervention',()=>ctx.openIntervention(d.id,'review')));card.append(node('p','Objective: '+d.objective),node('p','What we did / plan: '+d.action));if(ctx.recordLinks)card.append(ctx.recordLinks(d));card.append(button('Update measurement',()=>{ctx.navigate('deployments');ctx.openDeployment(d.id)}));const form=node('form',''),fields=node('div','','form-grid');const decision=field(fields,'review-'+d.id,'decision','Decision',r?.decision??'Collect evidence',{options:['Collect evidence','Expand','Revise','Stop']}),reviewer=field(fields,'review-'+d.id,'reviewer','Reviewer',r?.reviewer??''),notes=field(fields,'review-'+d.id,'notes','Review rationale',r?.notes??'',{type:'textarea'});const error=node('p','','small');error.setAttribute('role','alert');const save=node('button','Save outcome review','action primary');save.type='submit';form.append(fields,error,save);form.onsubmit=e=>{e.preventDefault();if(decision.value==='Expand'&&(!canExpand(d)||(d.outcomeEvidence&&!evidenceCurrent(d.outcomeEvidence,ctx.getEvidence?.())))){error.textContent='Expansion requires all readiness checks, a reached target, current dated evidence and a passed quality guardrail.';return}if(!reviewer.value.trim()||!notes.value.trim()){error.textContent='Reviewer and rationale are required.';return}const w=ctx.getWorkspace();w.outcomeReviews??=[];const record={deploymentId:d.id,decision:decision.value,reviewer:reviewer.value.trim(),notes:notes.value.trim(),reviewedAt:new Date().toISOString(),evidenceSnapshot:reviewFingerprint(d)};const i=w.outcomeReviews.findIndex(x=>x.deploymentId===d.id);if(i<0)w.outcomeReviews.push(record);else w.outcomeReviews[i]=record;ctx.saveWorkspace()};card.append(form);grid.append(card)}
 }return {render,open(id){selectedId=id;render()}};
}
