import {reviewFingerprint} from './outcome-review.mjs';
export function qbrSource(w){return JSON.stringify({goal:w.successPlan?.customerGoal,criteria:w.successPlan?.successCriteria,objectives:w.successPlan?.objectives??[],deployments:w.deployments.map(d=>reviewFingerprint(d)),reviews:w.outcomeReviews??[]})}
export function qbrText(w,narrative=''){
 const lines=['EXAMPLE CUSTOMER — REVIEWED QBR','Fictional account / synthetic evidence','', 'Customer goal',w.successPlan?.customerGoal||'Customer goal not recorded.','', 'Objectives',...(w.successPlan?.objectives??[]).map(o=>o.title),'','Reviewed observations'];
 for(const d of w.deployments){const r=w.outcomeReviews?.find(x=>x.deploymentId===d.id);if(!r||r.evidenceSnapshot!==reviewFingerprint(d))continue;lines.push(`${d.team}: ${d.metric}; baseline ${d.baseline}, target ${d.target}, observed ${d.actual??'unavailable'} ${d.unit}. Quality: ${d.quality}. Review decision: ${r.decision}.`)}
 if(!lines.some(x=>x.includes('Review decision:')))lines.push('No current reviewed outcomes available.');
 lines.push('','Decisions and next steps',narrative||'No additional narrative.','','Limitations','Synthetic, observational evidence. No causal productivity, quality or financial benefit is established. Internal notes and reproduction details are excluded.');return lines.join('\n');
}
export function approvalCurrent(w){const q=w.reviewedQbr;return !!q?.approval&&q.approval.source===qbrSource(w)&&q.approval.narrative===q.narrative}
export function mountReviewedQbr(ctx){const {node,button}=ctx,section=node('section','');section.dataset.screen='qbr';section.hidden=true;document.querySelector('main').append(section);const nav=node('button','Reviewed QBR','navbutton');nav.dataset.page='qbr';document.querySelector('nav').append(nav);
 const head=node('div','','heading');head.append(node('h1','Review before sharing.'));const notice=node('p','Manual local review only. Free-text claims are not automatically fact-checked. Internal notes, feedback and reproduction evidence are excluded from the generated brief.','internal-banner');const narrativeLabel=node('label','Customer-facing decisions / next steps'),narrative=document.createElement('textarea');narrative.maxLength=700;narrativeLabel.append(narrative);const reviewerLabel=node('label','Reviewer'),reviewer=document.createElement('input');reviewer.maxLength=100;reviewerLabel.append(reviewer);const confirmation=node('label',''),check=document.createElement('input');check.type='checkbox';confirmation.append(check,document.createTextNode(' I reviewed the claims, source evidence and customer-facing content.'));const status=node('p','','small');status.setAttribute('role','status');const preview=node('pre','','qbr-preview');let loaded=false;
 const approve=button('Approve current brief',()=>{const w=ctx.getWorkspace();if(!check.checked||!reviewer.value.trim()){status.textContent='Enter a reviewer and confirm the content review.';return}if(!w.successPlan?.customerGoal?.trim()){status.textContent='Record a customer goal first.';return}w.reviewedQbr={narrative:narrative.value,approval:{reviewer:reviewer.value.trim(),at:new Date().toISOString(),source:qbrSource(w),narrative:narrative.value}};ctx.saveWorkspace()});
 const download=button('Download reviewed brief',()=>{const w=ctx.getWorkspace();if(!approvalCurrent(w))return;const content=qbrText(w,w.reviewedQbr.narrative)+'\n\nReviewed by '+w.reviewedQbr.approval.reviewer+' at '+w.reviewedQbr.approval.at;const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='reviewed-qbr.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
 narrative.oninput=()=>{const w=ctx.getWorkspace();w.reviewedQbr??={};w.reviewedQbr.narrative=narrative.value;w.reviewedQbr.approval=null;check.checked=false;ctx.saveWorkspace()};section.append(head,notice,narrativeLabel,reviewerLabel,confirmation,approve,download,status,preview);
 function render(){const w=ctx.getWorkspace();if(!loaded){narrative.value=w.reviewedQbr?.narrative??'';loaded=true}const current=approvalCurrent(w);download.disabled=!current;status.textContent=current?'Reviewed locally by '+w.reviewedQbr.approval.reviewer:'Draft / review required. Source or narrative changes invalidate approval.';preview.textContent=qbrText(w,narrative.value);if(!current)check.checked=false}return {render};
}
