import {teams,diagnose,account,actions,branches} from '../prototype/diagnostic.mjs';
import {evidence} from '../prototype/evidence-data.mjs';
export async function runWorkflow(storage){
 const snapshot=await storage.get(),id=crypto.randomUUID(),at=new Date().toISOString();
 const plans=teams.map(t=>{const d=diagnose(t.c===null?{...t,c:0}:t);return {team:t.name,rule:branches[d.action],kind:d.action===1?'measurement_repair':'customer_intervention',action:actions[d.action],why:`Acceptance ${t.a}%; change ${d.delta} points; active share ${t.u}%.`,evidence_id:t.evidence_ids.join(', '),recommendationEvidence:evidence.records.filter(e=>e.team===t.name),baseline:t.a,metric:'agent_acceptance',success_criterion:'Agree a target, compare eligible windows and assess code-review quality.',target:null,quality:'Not assessed'}});
 for(const t of teams.filter(t=>t.c===null))plans.push({team:t.name,rule:'tracking-repair',kind:'measurement_repair',action:actions[1],why:'Contribution unavailable; adoption recommendation remains separate.',evidence_id:t.evidence_ids.join(', '),baseline:null,metric:'Verified tracking coverage',success_criterion:'Agree an inventory denominator and coverage target.',target:null,quality:'Not assessed'});
 const tasks=plans.map((p,i)=>({...p,id:`team-${i}-${encodeURIComponent(p.rule)}`,status:'Draft — target agreement required',owner:'Deployment manager / '+p.team+' lead',actual:null,created_by:'Internal execution'}));
 const run={id,at,status:'complete',source:'synthetic',mode:'deterministic offline',workspaceRevision:snapshot.revision,datasetVersion:evidence.datasetVersion,stages:[{name:'Customer triage',summary:`Adoption score ${(account().score?.toFixed(1)??'withheld')}; ${teams.filter(t=>diagnose(t).stalled).length} stalled teams. Synthetic evidence through ${evidence.window.end}. No causal productivity inference.`},{name:'Decision and solutions',plans},{name:'Internal execution',actions:tasks.map(t=>({team:t.team,result:'Draft retained or created; target agreement required'}))}]};await storage.saveRun(run,tasks);return run;
}
